name: Release

on:
  push:
    tags:
      - '*'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Version ID
      run: |
        VERSION=`git describe --tags --abbrev=0` || VERSION="SNAPSHOT-`git rev-parse --short HEAD`" ; echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Restore .NET dependencies
      run: dotnet restore
    - name: Setup GO
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4'
    - name: Restore GO modules
      run: | 
        cd ${{ github.workspace }}/ogame/cmd/ogamed
        go mod download
        cd ${{ github.workspace }}
      
    - name: Build TBot win64
      run: dotnet publish -c Release -r win-x64 -o publish/win64/ -p:PublishSingleFile=true --self-contained false
    - name: Build ogamed win64
      run: | 
        cd ${{ github.workspace }}/ogame/cmd/ogamed
        env GOOS=windows GOARCH=amd64 go build -o ogamed.exe
        cd ${{ github.workspace }}
        mv ${{ github.workspace }}/ogame/cmd/ogamed/ogamed.exe ${{ github.workspace }}/publish/win64/
    - name: Package win64
      uses: papeloto/action-zip@v1
      with:
        files: publish/win64/ README.md
        dest: TBot-${{ env.VERSION }}-win64.zip

    - name: Build TBot win32
      run: dotnet publish -c Release -r win-x86 -o publish/win32/ -p:PublishSingleFile=true --self-contained false
    - name: Build ogamed win32
      run: | 
        cd ${{ github.workspace }}/ogame/cmd/ogamed
        env GOOS=windows GOARCH=386 go build -o ogamed.exe
        cd ${{ github.workspace }}/
        mv ${{ github.workspace }}/ogame/cmd/ogamed/ogamed.exe ${{ github.workspace }}/publish/win32/
    - name: Package win32
      uses: papeloto/action-zip@v1
      with:
        files: publish/win32/ README.md
        dest: TBot-${{ env.VERSION }}-win32.zip
        
    - name: Build TBot linux-x64
      run: dotnet publish -c Release -r linux-x64 -o publish/linux-x64/ -p:PublishSingleFile=true --self-contained false
    - name: Build ogamed linux-x64
      run: | 
        cd ${{ github.workspace }}/ogame/cmd/ogamed
        env GOOS=linux GOARCH=amd64 go build -o ogamed
        cd ${{ github.workspace }}
        mv ${{ github.workspace }}/ogame/cmd/ogamed/ogamed ${{ github.workspace }}/publish/linux-x64/
        chmod +x ${{ github.workspace }}/publish/linux-x64/TBot
        chmod +x ${{ github.workspace }}/publish/linux-x64/ogamed
    - name: Package linux-x64
      uses: papeloto/action-zip@v1
      with:
        files: publish/linux-x64/ README.md
        dest: TBot-${{ env.VERSION }}-linux-x64.zip
        
    - name: Build TBot linux-arm
      run: dotnet publish -c Release -r linux-arm -o publish/linux-arm/ -p:PublishSingleFile=true --self-contained false
    - name: Build ogamed linux-arm
      run: | 
        cd ${{ github.workspace }}/ogame/cmd/ogamed
        env GOOS=linux GOARCH=arm GOARM=7 go build -o ogamed
        cd ${{ github.workspace }}
        mv ${{ github.workspace }}/ogame/cmd/ogamed/ogamed ${{ github.workspace }}/publish/linux-arm/
        chmod +x ${{ github.workspace }}/publish/linux-arm/TBot
        chmod +x ${{ github.workspace }}/publish/linux-arm/ogamed
    - name: Package linux-arm
      uses: papeloto/action-zip@v1
      with:
        files: publish/linux-arm/ README.md
        dest: TBot-${{ env.VERSION }}-linux-arm.zip

    - name: Build TBot linux-arm64
      run: dotnet publish -c Release -r linux-arm64 -o publish/linux-arm64/ -p:PublishSingleFile=true --self-contained false
    - name: Build ogamed linux-arm64
      run: | 
        cd ${{ github.workspace }}/ogame/cmd/ogamed
        env GOOS=linux GOARCH=arm64 go build -o ogamed
        cd ${{ github.workspace }}
        mv ${{ github.workspace }}/ogame/cmd/ogamed/ogamed ${{ github.workspace }}/publish/linux-arm64/
        chmod +x ${{ github.workspace }}/publish/linux-arm64/TBot
        chmod +x ${{ github.workspace }}/publish/linux-arm64/ogamed
    - name: Package linux-arm64
      uses: papeloto/action-zip@v1
      with:
        files: publish/linux-arm64/ README.md
        dest: TBot-${{ env.VERSION }}-linux-arm64.zip
        
    - name: Build TBot osx-x64
      run: dotnet publish -c Release -r osx-x64 -o publish/osx-x64/ -p:PublishSingleFile=true --self-contained false
    - name: Build ogamed osx-x64
      run: | 
        cd ${{ github.workspace }}/ogame/cmd/ogamed
        env GOOS=darwin GOARCH=amd64 go build -o ogamed
        cd ${{ github.workspace }}
        mv ${{ github.workspace }}/ogame/cmd/ogamed/ogamed ${{ github.workspace }}/publish/osx-x64/
        chmod +x ${{ github.workspace }}/publish/osx-x64/TBot
        chmod +x ${{ github.workspace }}/publish/osx-x64/ogamed
    - name: Package osx-x64
      uses: papeloto/action-zip@v1
      with:
        files: publish/osx-x64/ README.md
        dest: TBot-${{ env.VERSION }}-osx-x64.zip

    - name: Build TBot osx-arm64
      run: dotnet publish -c Release -r osx-arm64 -o publish/osx-arm64/ -p:PublishSingleFile=true --self-contained false
    - name: Build ogamed osx-arm64
      run: | 
        cd ${{ github.workspace }}/ogame/cmd/ogamed
        env GOOS=darwin GOARCH=arm64 go build -o ogamed
        cd ${{ github.workspace }}
        mv ${{ github.workspace }}/ogame/cmd/ogamed/ogamed ${{ github.workspace }}/publish/osx-arm64/
        chmod +x ${{ github.workspace }}/publish/osx-arm64/TBot
        chmod +x ${{ github.workspace }}/publish/osx-arm64/ogamed
    - name: Package osx-arm64
      uses: papeloto/action-zip@v1
      with:
        files: publish/osx-arm64/ README.md
        dest: TBot-${{ env.VERSION }}-osx-arm64.zip
        
    - name: Draft Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ github.workspace }}/TBot-${{ env.VERSION }}-win64.zip,${{ github.workspace }}/TBot-${{ env.VERSION }}-win32.zip,${{ github.workspace }}/TBot-${{ env.VERSION }}-linux-x64.zip,${{ github.workspace }}/TBot-${{ env.VERSION }}-linux-arm.zip,${{ github.workspace }}/TBot-${{ env.VERSION }}-linux-arm64.zip,${{ github.workspace }}/TBot-${{ env.VERSION }}-osx-x64.zip,${{ github.workspace }}/TBot-${{ env.VERSION }}-osx-arm64.zip
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
